### ISSUE TITLE
ubuntu 20.04 compiling error

### ISSUE THREAD

**Issue by sancelot** [mosra/corrade#109]
dpkg-buildpackage fails with next message :+1:  

> signfile corrade_2020.06.dsc
> gpg: skipped "Vladimír Vondruš <mosra@centrum.cz>": No secret key
> gpg: dpkg-sign.dHotbZi1/corrade_2020.06.dsc: clear-sign failed: No secret key
> 
> dpkg-buildpackage: error: failed to sign .dsc file

**Comment by mosra** [comment]
Hi!

It says "error", but it's more of a warning :) The `corrade*.deb` files should still get generated, one directory above. 

That being said, if you know a way how to skip signing / disable this annoying warning, please let me know :)

**Comment by sancelot** [comment]
Right. It has been generated.
