### ISSUE TITLE
Natvis for Corrade types

### ISSUE THREAD

**Issue by Squareys** [mosra/corrade#111]
For displaying Container types more conveniently when debugging in Visual Studio, I created a very very rudimentary .natvis file:

```xml
<?xml version="1.0" encoding="utf-8"?> 
<AutoVisualizer xmlns="http://schemas.microsoft.com/vstudio/debugger/natvis/2010">
  <Type Name="Corrade::Containers::Array&lt;*&gt;">
    <DisplayString>{{ size={_size} }}</DisplayString>
    <Expand>
      <ArrayItems>
        <Size>_size</Size>
        <ValuePointer>_data</ValuePointer>
      </ArrayItems>
    </Expand>
  </Type>
  <Type Name="Corrade::Containers::ArrayView&lt;*&gt;">
    <DisplayString>{{ size={_size} }}</DisplayString>
    <Expand>
      <ArrayItems>
        <Size>_size</Size>
        <ValuePointer>_data</ValuePointer>
      </ArrayItems>
    </Expand>
  </Type>
</AutoVisualizer>
```

Make sure to add it to your CMake project's sources so that Visual Studio picks it up.

Also, see the [Documentation of NatVis](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2015/debugger/create-custom-views-of-native-objects?view=vs-2015&redirectedfrom=MSDN).

**Comment by mosra** [comment]
More relevant links, in case someone wants to explore further -- ideal would be to make them embedded directly into PDBs when building Corrade itself (and then actually installing those as well):

- https://reviews.llvm.org/D48703
- https://gitlab.kitware.com/cmake/cmake/-/issues/16874

**Comment by mosra** [comment]
As of 759e3abcf86cfa1a039c782e739ec2ffdb84c7b1, this file is maintained in `src/debuggers/natvis/`. Thank you!
