### ISSUE TITLE
CMakeLists.txt:201

### ISSUE THREAD

**Issue by Wynadorn** [mosra/corrade#121]
My install of corrade failed with the following error log:
```
CMake Warning at CMakeLists.txt:201 (message):
  MSVC 2019 detected, automatically enabling MSVC2019_COMPATIBILITY.  Note
  that some features may not be available with this compiler.

CMake Warning at CMakeLists.txt:201 (message):
  MSVC 2019 detected, automatically enabling MSVC2019_COMPATIBILITY.  Note
  that some features may not be available with this compiler.

CMake Warning at CMakeLists.txt:201 (message):
  MSVC 2019 detected, automatically enabling MSVC2019_COMPATIBILITY.  Note
  that some features may not be available with this compiler.

[this repeats 100 times]

CMake Warning at CMakeLists.txt:201 (message):
  MSVC 2019 detected, automatically enabling MSVC2019_COMPATIBILITY.  Note
  that some features may not be available with this compiler.


ninja: error: manifest 'build.ninja' still dirty after 100 tries
```

Is the install failing on this warning message?

**Comment by mosra** [comment]
Hi, sorry for late reply -- holidays :)

I don't remember anybody running into this particular problem yet. Some ideas:

- Is Corrade a standalone CMake project or do you have it embedded as a subproject? If the latter, is it possible that it's somehow cyclically referencing itself? 
- Or do you use it from an IDE that could affect how CMake is run?  
- Or is it possible that some AV thingy, a background service, IDE project parser, etc. is touching the build files, causing Ninja to think something has been changed every time?

I remember Ninja geting stuck in a loop sometimes, but those are usually temporary issues that stopped when rerunning the command (been getting those on Travis CI macOS runners, I suspect some of their infrastructure did something with the filesystem that triggered this).

Hope this helps? :sweat_smile:

**Comment by jonesmz** [comment]
If you do ever run into ninja getting into a loop, if you could put the full build tree into an archive file, the ninja project would probably want that. They tend to be pretty attentive to that kind of bug.
