### ISSUE TITLE
what to set CORRADE_INCLUDE_DIR to for in-source-builds  

### ISSUE THREAD

**Issue by TrevorCash** [mosra/corrade#173]
Hi,

I am trying to build with cmake using in-source build.  So first I am using cmakes fetch_content, appending to CMAKE_MODULE_PATH, and then 
`add_subdirectory(corrade EXCLUDE_FROM_ALL)`

After that I call find_package(Corrade REQUIRED Main) and get the cmake error:

```
CMake Error at C:/Program Files/CMake/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Corrade (missing: CORRADE_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  build_debug/_deps/magnum-src/modules/FindCorrade.cmake:311 (find_package_handle_standard_args)

```
Is CORRADE_INCLUDE_DIR supposed to be defined before find_package?  

Thanks in advance

**Comment by mosra** [comment]
Hmm, this should "just work" if `fetch_content()` makes the binaries and includes available where CMake can find them. Shouldn't be needed to set anything explicitly.

**Comment by TrevorCash** [comment]
Shortly after posting I had realized I needed to usefetchcontent_makeavailable and it is working now.  Thanks
