### ISSUE TITLE
Container::Pointer does not work with forward declaration anymore

### ISSUE THREAD

**Issue by linuxaged** [mosra/corrade#181]
```
class BonvRenderer;
class Scene {
    Corrade::Containers::Pointer<BonvRenderer> _bonvRenderer;
}
```

Error: static assertion failed due to requirement 'Implementation::IsComplete<bon::BonvRenderer>::value': attempting to delete a pointer to an incomplete type corrade\src\Corrade\Containers\Pointer.h	299

**Comment by pezcode** [comment]
The implicit Scene destructor is defined inline by the compiler, at which point BonvRender is not yet defined. You need an explicit destructor (can be defaulted) at the point where BonvRender is defined.

```cpp
// Scene.h
class BonvRenderer;
class Scene {
public:
    ~Scene();
private:
    Corrade::Containers::Pointer<BonvRenderer> _bonvRenderer;
}
```

```cpp
// Scene.cpp
#include "BonvRender.h"

Scene::~Scene() = default;
```

**Comment by linuxaged** [comment]
thanks, just known it's explained in [corrade doc](https://doc.magnum.graphics/corrade/classCorrade_1_1Containers_1_1Pointer.html#Containers-Pointer-incomplete-types)
