### ISSUE TITLE
Shared library dependency

### ISSUE THREAD

**Issue by rwols** [mosra/corrade#20]
I installed corrade into /usr/local and now it cannot find libCorradeUtility.so.0. Here's the terminal output:

raoul@raoul:/usr/local/bin$ ldd corrade-rc 
	linux-vdso.so.1 =>  (0x00007ffdde75b000)
	libCorradeUtility.so.0 => not found
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f534dc06000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f534d900000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f534d6ea000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f534d325000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f534df0a000)

**Comment by rwols** [comment]
The libraries are installed in /usr/local/lib though:

raoul@raoul:/usr/local/lib$ ls | grep Corrade
libCorradeInterconnect.so
libCorradeInterconnect.so.0
libCorradeInterconnect.so.0.2
libCorradePluginManager.so
libCorradePluginManager.so.0
libCorradePluginManager.so.0.2
libCorradeTestSuite.so
libCorradeTestSuite.so.0
libCorradeTestSuite.so.0.2
libCorradeUtility.so
libCorradeUtility.so.0
libCorradeUtility.so.0.2

**Comment by mosra** [comment]
If you install to non-standard location, [you have to set the RPATH explicitly](http://mosra.cz/blog/corrade-doc/building-corrade.html#building-corrade-linux). So in your case pass the following argument to CMake:

```bash
cmake . -DCMAKE_INSTALL_RPATH=/usr/local/lib
```
