### ISSUE TITLE
installation via homebrew

### ISSUE THREAD

**Issue by lumpidu** [mosra/corrade#22]
Would be cool if one could just say brew install corrade on osx homebrew and it simply works ...

**Comment by mosra** [comment]
Done: https://github.com/mosra/homebrew-magnum

Install via:

    brew install --HEAD mosra/magnum/corrade

**Comment by lumpidu** [comment]
And finally the installation instructions on the main README ?

**Comment by mosra** [comment]
Done in dd3480f5a6516215d9fb27eac67203f6f89986d9. Docs will be uploaded in a batch later.
