### ISSUE TITLE
Compilation errors with BUILD_DEPRECIATED=OFF

### ISSUE THREAD

**Issue by Alicemargatroid** [mosra/corrade#24]
With GCC 5.3.1 (default on Ubuntu 16.04), the following errors occur if BUILD_DEPRECIATED=OFF

> 
> /home/ren/Desktop/ArcAngel2D/corrade/src/Corrade/Utility/utilities.h:66:26: error: ISO C++ forbids declaration of ‘CORRADE_DEPRECATED’ with no type [-fpermissive]
>  inline CORRADE_DEPRECATED("Use System::sleep() instead") void sleep(std::size_t ms) {
>                           ^
> /home/ren/Desktop/ArcAngel2D/corrade/src/Corrade/Utility/utilities.h:66:26: error: ‘Corrade::Utility::CORRADE_DEPRECATED’ declared as an ‘inline’ variable
> /home/ren/Desktop/ArcAngel2D/corrade/src/Corrade/Utility/utilities.h:66:56: error: invalid conversion from ‘const char*’ to ‘int’ [-fpermissive]
>  inline CORRADE_DEPRECATED("Use System::sleep() instead") void sleep(std::size_t ms) {
>                                                         ^
> /home/ren/Desktop/ArcAngel2D/corrade/src/Corrade/Utility/utilities.h:66:58: error: expected ‘,’ or ‘;’ before ‘void’
>  inline CORRADE_DEPRECATED("Use System::sleep() instead") void sleep(std::size_t ms) {
>                                                           ^
> 

Looks like -Wno-permissive would fix it, but it looks like GCC is getting smart enough to get around CORRADE_DEPRECATED logic.

**Comment by mosra** [comment]
Sorry about this, forgot to `#ifdef` the deprecated API properly. Fixed in 9c345e37cb254398d50966b33994141eecfda77d, similar issues were fixed in mosra/magnum@9b744250cfcd714dd23f8111d12e1a465c1c245c.

Seems like I'm getting old and forgetful.
