### ISSUE TITLE
Clang / Windows Build

### ISSUE THREAD

**Issue by dresch86** [mosra/corrade#40]
I would like to build with clang (llvm-windows). I don't see the options in the CMake to do so though as it defaults to MSVC. Can corrade be built with LLVM's clang?

**Comment by mosra** [comment]
@Squareys can you comment here? I don't remember the particulars or how far we got when we tried the last time.

**Comment by primesoftware** [comment]
I got it to work!! I added this toolset (https://github.com/WubbaLubba/LlvmForVS2017) to VS and used the command:

```
cmake -G"Visual Studio 15 2017" -T"LLVM-vs2017" ..
```

Then I followed the instructions on how to build the rest of the way. Now to see if I can get Magnum to work too...

**Comment by mosra** [comment]
Wow, this is amazing, thank you!

I think we should add this to the AppVeyor build now :)

**Comment by primesoftware** [comment]
I will have to see if the downloadable SDL dll will work with LLVM code otherwise in order to use clang/llvm with Magnum folks might have to rebuild their required libraries like SDL, GLFW, etc.

**Comment by mosra** [comment]
With b87f7ab1cedaf95651c644e522d2e78167de784f, cd9c0d23b0d0001648e82dcdc5ee8e8e86949dd2, 44915473ffccb268a20f3b241c043b28e66a944d, d0dfbfd21064bbf47f19f24b8ceb7622282cb1d7, c0c4a06ba7f2420a6a2274d6277c3753e1fb5d90, 3fc478e699d11cae9c227d3edf3596a0b867f29d, 94594b2eb5a72b6eff666e7779069f6841b47957, 3b4cade1ec878160a47aab3074161730cd7d7776 and 0280fbe42cdc74d8ceaebdad1a019709d00d36fa Corrade compiles on clang-cl cleanly without warnings and passes all tests. It's also tested on the CI now: https://magnum.graphics/build-status/.
