### ISSUE TITLE
MinGW Building

### ISSUE THREAD

**Issue by primesoftware** [mosra/corrade#41]
I decided to try building Corrade with MinGW (MSYS2 on Windows) first before giving it a go with Clang. I am getting the following error:

```
 Native `corrade-rc` executable, which is needed when crosscompiling, was
  not found
```
Isn't corrade-rc what gets built? Why is the builder looking for the program that its supposed to be compiling?

**Comment by mosra** [comment]
Huh, wtf, this should happen *only* if one is [crosscompiling](https://cmake.org/cmake/help/v3.0/variable/CMAKE_CROSSCOMPILING.html). What was your CMake invocation? Did you use some toolchain file that sets CMAKE_SYSTEM_NAME to something other than Windows?

**Comment by primesoftware** [comment]
The issue was that even though I was using an MSYS terminal it was still choosing the VS toolchain when building so that is why it thought it was crosscompiling. I've got everything straightened out now.
