### ISSUE TITLE
Console colors not working on macOS 10.14.5

### ISSUE THREAD

**Issue by marcizhu** [mosra/corrade#73]
The test suite example compiles and works fine on macOS 10.14.5, but colors are disabled for some reason. I tried compiling and running the code on Linux and colors are enabled there.

I just can't figure out why it works on one OS and not on the other when both of them use bash by default.

I attached a screenshot to show what I mean. This is not a big deal, but it would be nice to have cool colors working on macOS, Windows and Linux :)

<img width="892" alt="" src="https://user-images.githubusercontent.com/6199781/61592197-4757e280-abd0-11e9-98b7-6e5615f290f4.png">

**Comment by marcizhu** [comment]
Okay, I just read the documentation and I realize passing the parameter `--color on` to the application enables colors, but they are disabled by default (aka if nothing is passed or if `--color auto` is given to the application as a parameter). This behavior differs from for example Linux, where it is enabled if nothing or if `--color auto` is passed to it.

I'm sorry, I should have read the documentation before opening this issue. Reading the documentation I suspect the library is not detecting bash on macOS as an interactive TTY which *might* be an issue anyway. Is this behavior to be expected or is it some sort of minor bug?

**Comment by mosra** [comment]
Hi, thank you for the report!

> I'm sorry, I should have read the documentation before opening this issue

No worries. Yes, it seems that it's somehow related to TTY detection, but that one was definitely working last time I tried :) Unfortunately I don't have direct access to macOS right now, can you build Corrade with tests enabled (the `BUILD_TESTS` option in CMake) and then run `build/src/Corrade/Utility/Test/UtilityDebugTest` (or roughly around that location depending on your buildsystem)? There it has a bunch of tests for [Debug::isTty()](https://doc.magnum.graphics/corrade/classCorrade_1_1Utility_1_1Debug.html#a32458743e3d3731036378cf8577c7934), which does the TTY detection. Can you paste the relevant part of the test output here?

In that function, there's [a macOS-specific workaround](https://github.com/mosra/corrade/blob/9f44a793242e21555629b57e41e4d9fed515bb1c/src/Corrade/Utility/Debug.cpp#L238-L243) that aims to disable colors when running inside Xcode. There's no reliable way to detect that, so it checks for the `XPC_SERVICE_NAME` environment variable, which, according to my tests ~three years ago, was always set inside Xcode and never outside. Is there a possibility you have this var set in your Bash environment as well?

**Comment by marcizhu** [comment]
Even though I'm not using Xcode, somehow the variable `XPC_SERVICE_NAME` was set to 0. You're right! :)

After undefining it and running the example again, the colors are enabled by default. Also, I ran all the tests using `ctest` and all of them except `UtilityDirectoryTest` passed successfully, including `UtilityDebugTest`.

My guess is that some Xcode service running in the background sets this variable even if using bash directly (i.e. not compiling anything under Xcode). A possible solution might be to add an option to CMake to force enabling colors, or maybe just check the environment variable if we're building for Xcode. Or maybe just undefining that variable every time is okay too :)

I have some free time. I can test, debug and open a PR with a fix for this if you want. Oh, and thanks for the library! It's really nice, well documented and useful!

**Comment by mosra** [comment]
Thank you!

> all of them except `UtilityDirectoryTest` passed

I'd be interested in what failed there. The CI says [it's all good](https://magnum.graphics/build-status/), but that's just a statistical sample size of 1 :)

> A possible solution might be to add an option to CMake to force enabling colors

This should stay a runtime option. If you could figure out any other environment variable (or a combination of them) that would make this check more robust, that'd be great. Maybe there's some env var that's always set when running from Bash but never set when running from Xcode that could be used in addition to checking for `XPC_SERVICE_NAME`? Or maybe I just failed to google properly and there *is* a reliable way to detect if the exe is running inside Xcode?

**Comment by marcizhu** [comment]
This is the full output of `UtilityDebugTest` (with XPC_SERVICE_NAME disabled)  in case you need it:
```Starting Corrade::Utility::Test::DebugTest with 54 test cases...
Debug output is a TTY?   yes
Warning output is a TTY? yes
Error output is a TTY?   yes
    OK [01] isTty()
    OK [02] debug()
    OK [03] boolean()
    OK [04] ints<unsigned char>()
    OK [05] ints<char>()
    OK [06] ints<unsigned short>()
    OK [07] ints<short>()
    OK [08] ints<unsigned int>()
    OK [09] ints<int>()
    OK [10] ints<unsigned long>()
    OK [11] ints<long>()
    OK [12] ints<unsigned long long>()
    OK [13] ints<long long>()
    OK [14] floats<float>()
    OK [15] floats<double>()
    OK [16] floats<long double>()
    OK [17] chars()
    OK [18] pointer()
    OK [19] unicode()
    OK [20] custom()
    OK [21] flags()
    OK [22] nospace()
    OK [23] newline()
    OK [24] noNewlineAtTheEnd()
Black bold
    OK [25] colors(Black)
Red bold
    OK [26] colors(Red)
Green bold
    OK [27] colors(Green)
Yellow bold
    OK [28] colors(Yellow)
Blue bold
    OK [29] colors(Blue)
Magenta bold
    OK [30] colors(Magenta)
Cyan bold
    OK [31] colors(Cyan)
White bold
    OK [32] colors(White)
Default bold
    OK [33] colors(Default)
Default Green
    OK [34] colorsAutoReset()
Red Default
    OK [35] colorsExplicitReset()
Default Default
    OK [36] colorsDisabled()
Hello
Hello
    OK [37] colorsNospace()
This shouldn't be red.
  SKIP [38] colorsNoOutput()
        Only possible to test visually.
This should have default color.
This should be cyan.
This also and this blue.
This should be cyan again.
Disabling colors shouldn't affect outer scope, so also cyan.
And this resets back to default color.
    OK [39] colorsScoped()
The following should be shades of gray:
                ░░░░░░░░░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓████████████
    OK [40] valueAsColor()
The following should be uncolored shades of gray:
                ░░░░░░░░░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓████████████
    OK [41] valueAsColorColorsDisabled()
    OK [42] iterable()
    OK [43] iterableNested()
    OK [44] iterablePacked()
    OK [45] iterableNospace()
    OK [46] pair()
    OK [47] tuple()
    OK [48] iterablePairPacked()
    OK [49] iterableTuplePacked()
    OK [50] ostreamFallback()
    OK [51] ostreamFallbackPriority()
    OK [52] scopedOutput()
    OK [53] debugColor()
CORRADE_BUILD_MULTITHREADED defined: true
Output redirection visible in another thread: false
    OK [54] multithreaded()
Finished Corrade::Utility::Test::DebugTest with 0 errors out of 106 checks.
```

**Comment by mosra** [comment]
> Or maybe I just failed to google properly and there is a reliable way to detect if the exe is running inside Xcode?

Hmm, googling for `XPC_SERVICE_NAME`, it looks like many people have it defined in the shell, so it's not a reliable check at all :/ And checking if it's `0` or some other value doesn't seem like a good idea either.

**Comment by marcizhu** [comment]
> I'd be interested in what failed there. The CI says it's all good, but that's just a statistical sample size of 1 :)

This is what fails on that test:
<img width="945" src="https://user-images.githubusercontent.com/6199781/61628461-abd37a00-ac82-11e9-8ee1-51452bff4fb1.png">

> If you could figure out any other environment variable (or a combination of them) that would make this check more robust, that'd be great.

Maybe we could check against some other Xcode-specific variable, like `XCODE_PRODUCT_BUILD_VERSION`, `XCODE_VERSION_ACTUAL`, `XCODE_VERSION_MAJOR`, `XCODE_VERSION_MINOR`

**Comment by mosra** [comment]
What filesystem are you on? The test assumes it's HFS+ and there Apple does Unicode decomposition so e.g. `ě` is stored separately as `e` and a combining `ˇ` and so it's not bit-exact as what's in the source (but OTOH there's absolutely no difference in rendering, so it looks suspicious, hehe) -- I guess it would pass if you [invert the condition here](https://github.com/mosra/corrade/blob/9f44a793242e21555629b57e41e4d9fed515bb1c/src/Corrade/Utility/Test/DirectoryTest.cpp#L773-L780)?

> `XCODE_PRODUCT_BUILD_VERSION`, `XCODE_VERSION_ACTUAL`, `XCODE_VERSION_MAJOR`, `XCODE_VERSION_MINOR`

IIRC I didn't see any of those variables in the environment listing when running inside Xcode (otherwise I would use them, as they are vastly more self-explanatory than the `XPC_SERVICE_NAME`) :) But it was a long time ago, things could change since then. If you want to quickly try, `Utility::Debug{} << Utility::Arguments::environment();` prints all the env vars.

**Comment by marcizhu** [comment]
> I guess it would pass if you invert the condition here?

I tried it and it passes without any errors, your right once again.

I can't check for the environment variables myself because I don't have Xcode installed. I got those variables from [this gist](https://gist.github.com/gdavis/6670468), but it's from 2014 or something like that and I don't know how reliable it is or if those variables do even exist nowadays...

I'm trying to find an up-to-date list of environment variables defined by Xcode so we can fix this quick.

**Comment by marcizhu** [comment]
Is there any other option which doesn't involve checking for environment variables? I can't find any updated list with the variables defined by Xcode.

Maybe we could check which generator is using CMake. If we're building an Xcode project, then set a macro which disables colors by default (but could be forced with `--color on`). If not, just leave it enabled by default just like it is on Linux and other systems. This is a bit more work but seems more reliable to me than checking for an environment variable that we can't know for sure or may change in the near future :)

**Comment by mosra** [comment]
> I can't find any updated list with the variables defined by Xcode.

That list above doesn't have `XPC_SERVICE_NAME` at all and is much longer than I remember, I'm not sure if it's really the shell environment variables or some other variables (I suspect it's rather the variables you can reference from Xcode project files, not shell environment).

> Maybe we could check which generator is using CMake. If we're building an Xcode project, then set a macro which disables colors by default

That won't work for the (quite usual) case where you just take `*.dylib`s from Homebrew and put them into an Xcode project. The buildsystem can't make any assumption about how the resulting binary will get used.

> Is there any other option which doesn't involve checking for environment variables?

Found this: https://stackoverflow.com/a/39292112 ... can you pull from the `next` branch and try things out? Both the Directory test and this color stuff should be fixed there (c8d67d91187416fd7a7642896c5e8a11fc7509d9 and 6c1f013b023c664a2d3f6cd9c4d8ad2a38818cbf, for reference).

**Comment by marcizhu** [comment]
First of all, sorry for the late response 🙏
> can you pull from the next branch and try things out? Both the Directory test and this color stuff should be fixed there

Yup, fixed :) The 77 tests passed without any errors, `UtilityDebugTest` detects it is running on an interactive shell, and `UtilityDirectoryTest` no longer gives any failed case. Also colors are enabled by default as it should be.

I think we can merge the `next` branch to master, close this and we're good to go!

**Comment by mosra** [comment]
I would be more confident in the change if we could be sure that Xcode detection really works :sweat_smile:  Any chance you could install Xcode and try running one of the test executables in it?

**Comment by marcizhu** [comment]
Sure, I'm gonna install it and try if the code works there. Never used Xcode before, so I'll need some time 😅

**Comment by marcizhu** [comment]
Both the Xcode terminal window (left) and a bash shell (on the right), both working as intended:
<img width="1161" src="https://user-images.githubusercontent.com/6199781/61712714-384f6c80-ad57-11e9-8f48-32593d6907bd.png">

Looks good to me! :)

**Comment by mosra** [comment]
Thank you! Pushed to master.

**Comment by marcizhu** [comment]
Thank you for your time!
