### ISSUE TITLE
ArrayView construction from empty std::vector asserts

### ISSUE THREAD

**Issue by Squareys** [mosra/corrade#75]
As mentioned per gitter, the following code asserts on the vectors bounds check:

~~~cpp
#include <vector>
#include <Corrade/Containers/ArrayViewStl.h>
//...
std::vector<int> v;
ArrayView<int>(v);
~~~

As in line https://github.com/mosra/corrade/blob/master/src/Corrade/Containers/ArrayViewStl.h#L65 it tries to access element 0.

**Comment by mosra** [comment]
Tests added in b2a6e4b907d903952b501fefd9c2a1d100f4c171, fixed in ffa67c0d990d11bad64ff9d67e59fb981d0d9082. Didn't discover this myself because libstdc++'s `data()` is never `nullptr` so it was never blowing up.

Thanks a lot for reporting this.
