### ISSUE TITLE
Debug() goes silient after encountering with std::string in Debug mode

### ISSUE THREAD

**Issue by ttnghia** [mosra/corrade#86]
Hello,

Today I just found a bug. In Debug mode, when using the code like this:
```
Debug() << str;
```
where `str` is a `std::string`, then all callings to `Debug() << ...` from that line no longer output anything. Using `Debug()` with `const char*` does not suffer from this problem.

My compiler is MSVC 2019.
Note that if not in Debug mode (Release/RelDebugInfo) then I don't have this problem.

**Comment by mosra** [comment]
Huh. Is it possible that the string contained some non-printable character (a zero byte, carriage return and such)? A zero byte *could* explain this behavior -- with a `const char*` it'll only print everything until the zero delimiter, whereas with a string it'd continue further, possibly affecting the terminal in some weird way?

**Comment by ttnghia** [comment]
Nope. Just with any string, and the output stream stops right away:

``
std::string str = "test";
Debug() << str;
```

**Comment by mosra** [comment]
What. That's such a critical issue that I bet *some* tests would catch rather soon :D 

If you are able to build this repo and enable `BUILD_TESTS` in CMake, the `UtilityDebugTest` should trigger this.

Does it happen also if you do a minimal thing like this?

```cpp
#include <Corrade/Utility/DebugStl.h>

int main() {
    Debug{} << std::string{"test"} << 3<
}
```

Any difference when you `#include <Corrade/Utility/DebugStl.h>` or just `#include <Corrade/Utility/Debug.h>`?

**Comment by ttnghia** [comment]
```
#include <Corrade/Utility/DebugStl.h>

int main() {
    Corrade::Utility::Debug{} << std::string{ "test" } << 3;
}
```
Still the same problem: no thing output!

====================================================
```
#include <Corrade/Utility/Debug.h>
#include <string>

int main() {
    Corrade::Utility::Debug{} << std::string{ "test" } << 3;
}

```
This does not compile due to:

```
error C2678: binary '<<': no operator found which takes a left-hand operand of type 'Corrade::Utility::Debug' (or there is no acceptable
```

**Comment by ttnghia** [comment]
Ahhhhhhhhhhhh

I have figured out what's wrong: my app is always linked to CorradeUtility.lib (releasse build). It should be linked to CorradeUtility-d.lib.

Sorry! Now it can output normally.

**Comment by mosra** [comment]
Ah, right. The dreaded MSVC runtime libs :/

I wonder how many billions of dollars of developer time this ABI incompatibility in STL containers cost the past decades.
