### ISSUE TITLE
conan: Wrong version checked for "MSVC2017_COMPATIBILITY"

### ISSUE THREAD

**Issue by helmesjo** [mosra/corrade#93]
https://github.com/mosra/corrade/blob/f08be26ad2cb5f2d72c03783f8abc4d4abec8418/conanfile.py#L102

Just noticed this while glancing over. It should be 15, right?

Disclaimer: It has it's origin from [my recipe](https://github.com/helmesjo/conan-corrade/blob/7c17ef09cacc23270f64f9ae82d5766a45f93f3e/conanfile.py#L107)... :D

**Comment by mosra** [comment]
Isn't it 14.1? I don't know which of the seven versioning schemes Conan uses :) https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#Internal_version_numbering

**Comment by helmesjo** [comment]
Haha yep, that is a wild ride for sure. It should be the right (:point_right:) one. 
:upside_down_face:

**Comment by mosra** [comment]
Fixed in c0374146aa6efea19243be96c8e8aedd4aa27d36, also added the `MSVC2019_COMPATIBILITY` option that is new since last time.
