### ISSUE TITLE
error compiling current master because of Debug.cpp

### ISSUE THREAD

**Issue by underdoeg** [mosra/corrade#97]
Error message is
``` c++
use of deleted function ‘std::basic_ostream<char, _Traits>& std::operator<<(std::basic_ostream<char, _Traits>&, char32_t) [with _Traits = std::char_traits<char>]’
```

System is an up to date arch. g++ 10.1.0

uncommenting this line "fixes" the issue
https://github.com/mosra/corrade/blob/master/src/Corrade/Utility/Debug.cpp#L551

**Comment by mosra** [comment]
Thanks! I'm still on GCC 9, so this is new to me. Will update my Arch and check why this happens -- honestly not sure why such function would be deleted, neither libc++ nor MSVC STL has any problem with that :thinking:

**Comment by mosra** [comment]
Ah, that's a new thing in C++20: https://en.cppreference.com/w/cpp/io/basic_ostream/operator_ltlt2

I don't understand why anyone would want such behavior, but whatever (I don't get the point of 90% of the stuff added in C++17 and up, especially the insanities with `std::byte` or `char8_t`). Before I am able to upgrade -- if you do the following, does it compile?

```patch
diff --git a/src/Corrade/Utility/Debug.cpp b/src/Corrade/Utility/Debug.cpp
index fb538c67..5d1d9e99 100644
--- a/src/Corrade/Utility/Debug.cpp
+++ b/src/Corrade/Utility/Debug.cpp
@@ -561,7 +561,7 @@ Debug& Debug::operator<<(long double value) {
 
 Debug& Debug::operator<<(char32_t value) {
     std::ostringstream o;
-    o << "U+" << std::hex << std::uppercase << std::setw(4) << std::setfill('0') << value;
+    o << "U+" << std::hex << std::uppercase << std::setw(4) << std::setfill('0') << std::uint32_t(value);
     return print(o.str());
 }
 
```

**Comment by underdoeg** [comment]
I kinda get wanting a difference between byte and char. but yeah breaking backwards compatibility like that is not great.
Your fix seems to work though. thanks

**Comment by mosra** [comment]
Great, pushed as ea3fd5374288d30db37fcab7c05b3be98f815cfe :)
